source 'https://rubygems.org'
# ruby '2.6.5'

gem 'rails', '~> 6.1.4'
gem 'pg'
gem 'sass-rails'
gem 'uglifier', '>= 4.2.0'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'therubyracer', '~> 0.12.3'
gem 'jbuilder', '~> 2.9.0'
gem 'sdoc', group: :doc
gem 'puma', '5.6.1'
gem 'haml'
gem 'haml-rails'
gem 'redis-rails'
gem 'devise'
gem 'devise_invitable'
gem 'cancancan'
gem 'simple_form'
gem 'bootstrap-sass'
gem 'ffaker'
gem 'textacular'
gem 'jquery-turbolinks'
gem 'ckeditor', '~> 4.1', '>= 4.1.5'
gem 'paperclip'
gem 'rmagick'
gem 'activerecord-session_store'

gem 'friendly_id'
gem 'country_select', '2.4.0'
gem 'annotate'
gem 'form_errors'
gem 'responders'
gem 'email_validator'
gem 'font-awesome-rails'
gem 'commontator'
gem 'will_paginate'
gem 'figaro'
# gem 'aws-sdk-v1'
gem 'aws-sdk', '~> 3'
gem 'cocoon'
gem 'filterrific'
gem 'will_paginate-bootstrap'
gem 'stripe', '~> 1.30'
gem 'paypal-sdk-rest', '~> 1.3.0'
gem 'mathjax-rails'
gem 'bootstrap-datepicker-rails'
gem 'momentjs-rails'
gem 'moment_timezone-rails'
gem 'bootstrap3-datetimepicker-rails'
gem 'chosen-rails'
gem 'active_record_union'
gem 'active_elastic_job'
gem 'select2-rails'
gem 'rack-rewrite'
gem 'html2doc'
gem 'spreadsheet'
gem 'paperclip-av-transcoder'
gem 'jquery-fileupload-rails'
# gem 'mediaelement-qualityselector', git: 'https://github.com/cjcolvar/mediaelement-qualityselector'
# gem 'mediaelement_rails'
# gem 'bower-rails'
#gem 'paperclip-ffmpeg', '~> 1.2.0'
gem 'videojs_rails'
gem 'premailer-rails'
gem 'acts_as_tree'
gem 'pundit'
#gem 'pdfjs_rails', git: 'https://github.com/dano000/pdfjs_rails', branch: 'ys-branch'
gem 'pdfjs_viewer-rails'
gem 'rubyzip'
gem 'caxlsx'
gem 'caxlsx_rails'
gem "braintree"

gem 'prawn'
gem 'prawn-table'
gem 'sentry-raven'
gem 'aws-healthcheck'
gem 'canonical-rails'
gem 'sitemap_generator'
gem 'ratyrate'
# gem 'english', '~> 0.6.3', :require => false

gem 'whenever', :require => false
gem "recaptcha",'4.0.1', require: "recaptcha/rails"
gem 'jquery-datatables-rails', '~> 3.4.0'

# never include in :development !

gem 'bootstrap-social-rails'
gem 'nested_form'
gem 'jquery-validation-rails'
gem 'has_scope'
gem 'devise-security'
gem 'active-record-profiler'
gem 'js_cookie_rails'
gem 'newrelic_rpm'
gem 'rack-host-redirect'
gem 'toastr_rails'
gem 'bootstrap-tooltip-rails'
gem 'browser'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary', '0.12.4'
gem 'invisible_captcha'
gem 'combine_pdf'
gem 'pdf-reader'
gem 'exception_notification'
gem 'rack-attack'
gem 'bootsnap'
gem 'rails-controller-testing'
gem "webpacker"
gem 'gon'
#gem 'simplecov', require: false, group: :test

group :development, :test do
  gem 'byebug'
  gem 'pry-rails', '0.3.4'
  gem 'rspec-rails'
  gem 'shoulda-matchers', '2.8.0'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'capybara'
  gem 'database_cleaner', '~> 1.5.0'
  gem 'selenium-webdriver'
  gem 'cucumber-rails', :require => false
  gem 'parallel_tests'
  gem 'timecop'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 3.2'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'guard-bundler', require: false
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'better_errors', '~> 2.1.1'
  gem 'erb2haml'
  gem 'awesome_print'
  gem 'meta_request'
  #gem 'bullet' doe not support rails 6 yet
  gem 'rubocop', require: false
  gem 'rubocop-git'
  gem 'letter_opener'
end
gem 'sprockets', '3.7.2'
