# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3093c29a19f0de9fafa678f901a22087a717aae388aaa0fd5a838215cf81ca4a27cb5d943da43ba7f9917a96ddeeeb348185366d88104d291fe31ec2af9e9ecf
  paypal_host: https://www.sandbox.paypal.com
  # set your own app host or use url
  app_host: http://localhost:3000
  recaptcha_public_key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
  recaptcha_private_key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe


test:
  secret_key_base: dce3720da3dce8dc67bf0961f0dc03a898a8854e70db8ed07821e454cbd7551c189d4298d74287e3b867184911fe36c14e67ba18d31ba3060e66486e088d2e51
  recaptcha_public_key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
  recaptcha_private_key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
# Do not keep production secrets in the repository,
# instead read values from the environment.

stage:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  # paypal_host: https://www.paypal.com
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://stage.gradready.com.au
  recaptcha_public_key: <%= ENV["RECAPTCHA_PUBLIC_KEY"] %>
  recaptcha_private_key: <%= ENV["RECAPTCHA_PRIVATE_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  # paypal_host: https://www.paypal.com
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://beta.gradready.com.au
  recaptcha_public_key: <%= ENV["RECAPTCHA_PUBLIC_KEY"] %>
  recaptcha_private_key: <%= ENV["RECAPTCHA_PRIVATE_KEY"] %>
