require 'rubygems'
require 'sitemap_generator'

SitemapGenerator::Sitemap.default_host = 'https://gradready.com.au'
SitemapGenerator::Sitemap.create do
  add '/home', :changefreq => 'daily', :priority => 0.9
  add '/faq', :changefreq => 'daily'
  add '/gamsat', :changefreq => 'daily'
  add '/gamsat/gamsat_readies/online-basic', :changefreq => 'daily'
  add '/gamsat/gamsat_readies/online', :changefreq => 'daily'
  add '/gamsat/gamsat_readies/attendence-basic', :changefreq => 'daily'
  add '/gamsat/gamsat_readies/attendence-all', :changefreq => 'daily'
  add '/gamsat/gamsat_readies/custom', :changefreq => 'daily'
  add '/gamsat/gamsat_readies/interviewready-comprehensive', :changefreq => 'daily'
  add '/gamsat/scholarship', :changefreq => 'daily'
  add '/gamsat/compare', :changefreq => 'daily'
  add '/gamsat/about', :changefreq => 'daily'
  add '/gamsat/team', :changefreq => 'daily'
  add '/updates', :changefreq => 'daily'
  add '/gamsat/our_students', :changefreq => 'daily'
  add '/gamsat/student_testimonials', :changefreq => 'daily'
  add '/gamsat/faq', :changefreq => 'daily'
  add '/blog/gamsat', :changefreq => 'daily'
  add '/gamsat/contact', :changefreq => 'daily'
  add '/umat/scholarship', :changefreq => 'daily'
  add '/umat/compare', :changefreq => 'daily'
  add '/umat/about', :changefreq => 'daily'
  add '/umat/team', :changefreq => 'daily'
  add '/umat/faq', :changefreq => 'daily'
  add '/blog/umat', :changefreq => 'daily'
  add '/umat/contact', :changefreq => 'daily'
  add '/vce/scholarship', :changefreq => 'daily'
  add '/vce/compare', :changefreq => 'daily'
  add '/vce/about', :changefreq => 'daily'
  add '/vce/team', :changefreq => 'daily'
  add '/vce/faq', :changefreq => 'daily'
  add '/blog/vce', :changefreq => 'daily'
  add '/vce/contact', :changefreq => 'daily'
  add '/hsc/scholarship', :changefreq => 'daily'
  add '/hsc/compare', :changefreq => 'daily'
  add '/hsc/about', :changefreq => 'daily'
  add '/hsc/team', :changefreq => 'daily'
  add '/hsc/faq', :changefreq => 'daily'
  add '/blog/hsc', :changefreq => 'daily'
  add '/hsc/contact', :changefreq => 'daily'
end
