require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FaqPagesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FaqPage. As you add validations to FaqPage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:user) { FactoryGirl.create(:user, :admin) }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FaqPagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before do
    sign_in user
  end

  describe "GET #index" do
    it "assigns all faq_pages as @faq_pages" do
      faq_page = FaqPage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:faq_pages)).to eq([faq_page])
    end
  end

  describe "GET #show" do
    it "assigns the requested faq_page as @faq_page" do
      faq_page = FaqPage.create! valid_attributes
      get :show, {:id => faq_page.to_param}, valid_session
      expect(assigns(:faq_page)).to eq(faq_page)
    end
  end

  describe "GET #new" do
    it "assigns a new faq_page as @faq_page" do
      get :new, {type: 'gamsat'}, valid_session
      expect(assigns(:faq_page)).to be_a_new(FaqPage)
    end
  end

  describe "GET #edit" do
    it "assigns the requested faq_page as @faq_page" do
      faq_page = FaqPage.create! valid_attributes
      get :edit, {:id => faq_page.to_param}, valid_session
      expect(assigns(:faq_page)).to eq(faq_page)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FaqPage" do
        expect {
          post :create, {:faq_page => valid_attributes}, valid_session
        }.to change(FaqPage, :count).by(1)
      end

      it "assigns a newly created faq_page as @faq_page" do
        post :create, {:faq_page => valid_attributes}, valid_session
        expect(assigns(:faq_page)).to be_a(FaqPage)
        expect(assigns(:faq_page)).to be_persisted
      end

      it "redirects to the created faq_page" do
        post :create, {:faq_page => valid_attributes}, valid_session
        expect(response).to redirect_to(FaqPage.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved faq_page as @faq_page" do
        post :create, {:faq_page => invalid_attributes}, valid_session
        expect(assigns(:faq_page)).to be_a_new(FaqPage)
      end

      it "re-renders the 'new' template" do
        post :create, {:faq_page => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested faq_page" do
        faq_page = FaqPage.create! valid_attributes
        put :update, {:id => faq_page.to_param, :faq_page => new_attributes}, valid_session
        faq_page.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested faq_page as @faq_page" do
        faq_page = FaqPage.create! valid_attributes
        put :update, {:id => faq_page.to_param, :faq_page => valid_attributes}, valid_session
        expect(assigns(:faq_page)).to eq(faq_page)
      end

      it "redirects to the faq_page" do
        faq_page = FaqPage.create! valid_attributes
        put :update, {:id => faq_page.to_param, :faq_page => valid_attributes}, valid_session
        expect(response).to redirect_to(faq_page)
      end
    end

    context "with invalid params" do
      it "assigns the faq_page as @faq_page" do
        faq_page = FaqPage.create! valid_attributes
        put :update, {:id => faq_page.to_param, :faq_page => invalid_attributes}, valid_session
        expect(assigns(:faq_page)).to eq(faq_page)
      end

      it "re-renders the 'edit' template" do
        faq_page = FaqPage.create! valid_attributes
        put :update, {:id => faq_page.to_param, :faq_page => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested faq_page" do
      faq_page = FaqPage.create! valid_attributes
      expect {
        delete :destroy, {:id => faq_page.to_param}, valid_session
      }.to change(FaqPage, :count).by(-1)
    end

    it "redirects to the faq_pages list" do
      faq_page = FaqPage.create! valid_attributes
      delete :destroy, {:id => faq_page.to_param}, valid_session
      expect(response).to redirect_to(faq_pages_url)
    end
  end

end
