require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe McqAttemptsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # McqAttempt. As you add validations to McqAttempt, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # McqAttemptsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all mcq_attempts as @mcq_attempts' do
      mcq_attempt = McqAttempt.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:mcq_attempts)).to eq([mcq_attempt])
    end
  end

  describe 'GET #reivew' do
    it 'assigns all mcq_attempts as @mcq_attempts' do
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested mcq_attempt' do
        mcq_attempt = McqAttempt.create! valid_attributes
        put :update, { id: mcq_attempt.to_param, mcq_attempt: new_attributes }, valid_session
        mcq_attempt.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested mcq_attempt as @mcq_attempt' do
        mcq_attempt = McqAttempt.create! valid_attributes
        put :update, { id: mcq_attempt.to_param, mcq_attempt: valid_attributes }, valid_session
        expect(assigns(:mcq_attempt)).to eq(mcq_attempt)
      end

      it 'redirects to the mcq_attempt' do
        mcq_attempt = McqAttempt.create! valid_attributes
        put :update, { id: mcq_attempt.to_param, mcq_attempt: valid_attributes }, valid_session
        expect(response).to redirect_to(mcq_attempt)
      end
    end

    context 'with invalid params' do
      it 'assigns the mcq_attempt as @mcq_attempt' do
        mcq_attempt = McqAttempt.create! valid_attributes
        put :update, { id: mcq_attempt.to_param, mcq_attempt: invalid_attributes }, valid_session
        expect(assigns(:mcq_attempt)).to eq(mcq_attempt)
      end

      it "re-renders the 'edit' template" do
        mcq_attempt = McqAttempt.create! valid_attributes
        put :update, { id: mcq_attempt.to_param, mcq_attempt: invalid_attributes }, valid_session
        expect(response).to render_template('edit')
      end
    end
  end
end
