class EmailDelivery < ApplicationRecord
  filterrific(
    available_filters: [
      :with_start,
      :with_end
    ]
  )

  scope :with_start, -> (start_date){
    where('email_deliveries.created_at >= ?', start_date.to_date.beginning_of_day)
  }

  scope :with_end, -> (end_date){
    where('email_deliveries.created_at <= ?', end_date.to_date.end_of_day)
  }

	def self.log(mailer_action, message)
    trigger_name, category, recipient = self.get_category_trigger_points(mailer_action)
    body = message.body
    body = message.as_json["body"]["parts"][0]["body"]["raw_source"] if message.parts.present?
    category = "Gc Support Tickets" if category == "ticket"
    EmailDelivery.create(recipient: recipient, from: self.comma_separated(message.from), body: body, category: category, trigger_name: trigger_name, subject: message.subject)
  end

  private
  def self.comma_separated(arr)
    if !arr.nil? && !arr.empty?
      arr.join(",")
    else
      ""
    end
  end

  def self.get_category_trigger_points(action)
    case action.to_s
    when "announcement_email"
      trigger_point = "manual announcement email from admin"
      category = "Announcements"
      recipient  = "selected product versions students"
    when "blog_mail_to_student"
      trigger_point = "On creating a Blog Post"
      category = "Blog Post"
      recipient  = "All the Blog subscribers, Users with active course and Enquiry Users within last one year"
    when "welcome_subscription"
      trigger_point = "On subscribing blog"
      category = "Blog Post"
      recipient  = "User who subscribed"
    when "appointment_escalate_mail_to_staff"
      trigger_point = "Escalating Appointment (if no response received from the appointed staff)"
      category = "Private Tutoring"
      recipient  = "tutor who is escalated, quality.assurance@gradready.com.au"
    when "appointment_escalate_mail_to_student"
      trigger_point = "Escalating Appointment (if no response received from the appointed staff)"
      category = "Private Tutoring"
      recipient  = "Student who has escalated the tutor"
    when "check_response_regarding_appointment"
      trigger_point = "Background job to send escalation reminder email to students after 48 hours of appointment"
      category = "Private Tutoring"
      recipient  = "Student who has Appointed the staff"
    when "make_student_booking"
      trigger_point = "On making Appointment"
      category = "Private Tutoring"
      recipient  = "Student who made appointment"
    when "make_tutor_booking"
      trigger_point = "On making Appointment"
      category = "Private Tutoring"
      recipient  = "Staff who has been appointed by student"
    when "course_full_alert"
      trigger_point = "New Enrolments, Course Transfer, Feature log purchase, Addon purchase on course (if 2 enrolment left in full class size)"
      category = "Enrolment"
      recipient  = "payment@gradready.com.au,'michael.qiu@gradready.com.au"
    when "course_full_notification"
      trigger_point = "New Enrolments, Course Transfer, Feature log purchase, Addon purchase on course (if class size is full)"
      category = "Enrolment"
      recipient  = "payment@gradready.com.au"
    when "expiry_notification"
      trigger_point = "Background job to check course expired"
      category = "Enrolment"
      recipient  = "Students who has enrolled in the course expired"
    when "expiry_notification_before_7_days"
      trigger_point = "Background job to check course expire before 7 days"
      category = "Enrolment"
      recipient  = "Students who has enrolled in the course about to expire"
    when "inform_new_staff"
      trigger_point = "Updating staff profiles in course"
      category = "Course Management"
      recipient  = "New staff member if any"
    when "inform_old_staff"
      trigger_point = "Updating staff profiles in course"
      category = "Course Management"
      recipient  = "Old staff member if any"
    when "live_classes_mail"
      trigger_point = "Background job to send mail for live classes on same day"
      category = "Course Management"
      recipient  = "student enrolled in live classes course"
    when "mock_classes_mail"
      trigger_point = "Background job to send mail for mock classes on same day"
      category = "Course Management"
      recipient  = "student enrolled in mock classes course"
    when "discount_link_auto_email"
      trigger_point = "Any new purchase made like course, feature logs"
      category = "Enrolment"
      recipient  = "Student who made purchase"
    when "enrolment_order_received"
      trigger_point = "On making payment via bank/paypal"
      category = "Payment"
      recipient  = "Student who made purchase"
    when "send_free_trial_expiry_mail_after_14_days"
      trigger_point = "After 14 days of registration in free trial. (background job)"
      category = "NA"
      recipient  ="student enrolled in free trial only and has not purchased a course/add-on "
    when "free_trial_expiry_mail_today"
      trigger_point = "Background Job to send course expire mail on same day(code is commented)"
      category = "Course Management"
      recipient  = "Student who enrolled in course"
    when "staff_new_enrolment"
      trigger_point = "Any new purchase made like course, feature logs"
      category = "Enrolment"
      recipient  = "payment@gradready.com.au"
    when "student_new_customise_enrolment"
      trigger_point = "New enrolment or course transfer as per set from ADMIN"
      category = "Custom Email"
      recipient  = "Student who made purchase"
    when "student_new_enrolment"
      trigger_point = "Any new purchase made like course, feature logs"
      category = "Enrolment"
      recipient  = "Student who made purchase"
    when "student_new_free_trial_enrolment"
      trigger_point = "Free trial signup"
      category = "Course Management"
      recipient  = "Student who enrolled in free trial"
    when "unenrollment_notification"
      trigger_point = "Expired courses and free trial"
      category = "Course Management"
      recipient  = "Student who is enrolled in course"
    when "essay_feedback_tutor_rating"
      trigger_point = "Essay feedback by student"
      category = "Essay Marking"
      recipient  = "quality.assurance@gradready.com.au, tutor to whom essay feedback is assigned"
    when "essay_marking_reminder"
      trigger_point = "User signup, New Enrolment, Delete Enrolment, Background Job"
      category = "Essay Marking"
      recipient  = "Staff profiles who to whom course is assigned"
    when "essay_reminder"
      trigger_point = "Background Job"
      category = "Essay Marking"
      recipient  = "quality.assurance@gradready.com.au, tutor to whom essay was assigned, essay.coordinator@gradready.com.au"
    when "expiry_reminder"
      trigger_point = "Background Job before 7 days of essay expire date"
      category = "Essay Marking"
      recipient  = "Student"
    when "expiry_reminder_before_2_days"
      trigger_point = "Background Job before 2 days of essay expire date"
      category = "Essay Marking"
      recipient  = "Student"
    when "inform_old_tutor"
      trigger_point = "Update assigned tutor for essay marking"
      category = "Essay Marking"
      recipient  = "Old tutor assigned"
    when "marked_essay"
      trigger_point = "When tutor respond to essay"
      category = "Essay Marking"
      recipient  = "Essay's student"
    when "new_tutor_assigned"
      trigger_point = "Update assigned tutor for essay marking"
      category = "Essay Marking"
      recipient  = "New tutor assigned"
    when "test_essay_reminder"
      trigger_point = "Background Job to send test email"
      category = "NA"
      recipient  = "NA"
    when "unmarked_essay"
      trigger_point = "Essay submission by student"
      category = "Essay Marking"
      recipient  = "Tutor to whom essay is assigned"
    when "feedback_comment_by_student"
      trigger_point = "Comment by student on essay feedback"
      category = "Essay Marking"
      recipient  = "Tutor who responded on Essay or Marked essay"
    when "feedback_comment_by_tutor"
      trigger_point = "Comment by tutor on essay feedback"
      category = "Essay Marking"
      recipient  = "Student who submitted essay"
    when "job_application_submitted"
      trigger_point = "New Job Application"
      category = "Job Application"
      recipient  = "Candidate who applied for job"
    when "rejected_job_application"
      trigger_point = "Job Application Rejected"
      category = "Job Application"
      recipient  = "Candidate who applied for job"
    when "send_initial_assessment"
      trigger_point = "Sending initial assessment on job application"
      category = "Job Application"
      recipient  = "Candidate who applied for job"
    when "student_job_application"
      trigger_point = "New Job Application"
      category = "Job Application"
      recipient  = "hr@gradready.com.au"
    when "successful_job_application"
      trigger_point = "Job application status updated to 3.1 Successful Interview"
      category = "Job Application"
      recipient  = "Candidate who applied for job"
    when "unsuccessful_job_application"
      trigger_point = "Job application status updated to 3.2 Unsuccessful Interview"
      category = "Job Application"
      recipient  = "Candidate who applied for job"
    when "to_review"
      trigger_point = "New MCQ stem"
      category = "MCQ stem"
      recipient  = "MCQ stem reviewer"
    when "new_mock_essays"
      trigger_point = "New mock exam essay"
      category = "Mock Essay"
      recipient  = "All tutors assigned to this essay"
    when "partial_feeback_mail"
      trigger_point = "Background Job to send mail if essay feedback was provided 3 days ago and not yet marked"
      category = "Mock Essay"
      recipient  = "essay.coordinator@gradready.com.au, assigned tutor to this essay"
    when "send_overdue_reminder"
      trigger_point = "Background Job to send mail on Mock exam overdue date"
      category = "Mock Essay"
      recipient  = "essay.coordinator@gradready.com.au, quality.assurance@gradready.com.au, assigned tutor"
    when "tutor_feedback"
      trigger_point = "Mock essay marked"
      category = "Mock essay"
      recipient  = "Assigned student"
    when "customise_master_feature_mail"
      trigger_point = "on purchase of master feature"
      category = "Custom email"
      recipient  = "Student who made purchase"
    when "promo_applied"
      trigger_point = "when promo is applied on any order"
      category = "Order"
      recipient  = "accounts@gradready.com.au"
    when "promo_shared"
      trigger_point = "Sharing promo code by student"
      category = "Promo code"
      recipient  = "Email submitted by student to share"
    when "staff_complete_purchase"
      trigger_point = "Purchase done by student"
      category = "Payment"
      recipient  = "payment@gradready.com.au"
    when "staff_new_banktrans"
      trigger_point = "New purchase done by student using bank transfer"
      category = "Payment"
      recipient  = "payment@gradready.com.au"
    when "student_tax_invoice"
      trigger_point = "When student's payment has been confirmed "
      category = "Payment"
      recipient  = "Student who made purchase"
    when "trial_course_congratulation"
      trigger_point = "Activate Trial Course"
      category = "Enrolment"
      recipient  = "Student who purchase trial course"
    when "unsuccessful_purchase"
      trigger_point = "unsuccessful purchase done by student"
      category = "Payment"
      recipient  = "Student who made purchase"
    when "rating_feedback"
      trigger_point = "When rating MCQ Stem, MCQ, Video"
      category = "Rating"
      recipient  = "quality.assurance@gradready.com.au"
    when "shipping_confirmation_mail"
      trigger_point = "creating or updating textbook deliveries"
      category = "Textbook Delivery"
      recipient  = "Student for whom textbook delivery is updated"
    when "answer_to_assigned_ticket"
      trigger_point = "When a tutor respond to a ticket"
      category = "Ticket"
      recipient  = "Tutor to whom ticket was assigned"
    when "check_response_regarding_question"
      trigger_point = "Background Job to check if student received reply on ticket after 48 hours"
      category = "Ticket"
      recipient  = "Student who raised ticket"
    when "confirm_ticket_sent"
      trigger_point = "On raising ticket by student"
      category = "Ticket"
      recipient  = "Student"
    when "escalate_mail_to_staff"
      trigger_point = "When student escalate an issue"
      category = "Ticket"
      recipient  = "assigned tutor/staff,  escalations@gradready.com.au"
    when "escalate_mail_to_student"
      trigger_point = "Escalation confirmation when student escalate an issue"
      category = "Ticket"
      recipient  = "Student who escalated issue"
    when "new_answer"
      trigger_point = "When a tutor respond to a ticket"
      category = "Ticket"
      recipient  = "Student who asked question"
    when "new_comment_assignee"
      trigger_point = "when any student comment on a ticket"
      category = "Ticket"
      recipient  = "Tutor to whom ticket was assigned"
    when "new_comment_student"
      trigger_point = "When any tutor comment  on ticket"
      category = "Ticket"
      recipient  = "student who asked the question"
    when "new_comment_tutor"
      trigger_point = "When any tutor comment  on ticket"
      category = "Ticket"
      recipient  = "Tutor who commented on ticket"
    when "new_question"
      trigger_point = "When student raise a ticket"
      category = "Ticket"
      recipient  = "answerer/staff whom ticket is assigned"
    when "new_question_reminder"
      trigger_point = "Background Job to check response"
      category = "Ticket"
      recipient  = "quality.assurance@gradready.com.au, answerer/staff whom ticket is assigned"
    when "new_question_with_answerer"
      trigger_point = "NA (Trigger the new question email)"
      category = "NA"
      recipient  = "NA"
    when "ticket_follow_up_mail"
      trigger_point = "Background job if follow up required on ticket and a date is set"
      category = "Ticket"
      recipient  = "'quality.assurance@gradready.com.au', Ticket answerer mail"
    when "ticket_resolved"
      trigger_point = "When ticket is resolved by a tutor"
      category = "Ticket"
      recipient  = "Student who asked question"
    when "transfer_ticket"
      trigger_point = "Ticket transfer to new tutor/staff"
      category = "Ticket"
      recipient  = "the transferee and transferer of the ticket"
    when "unresolved_reminder"
      trigger_point = "Background job - 48 hours after the ticket hasn't been answered"
      category = "Ticket"
      recipient  = "answerer of ticket"
    when "feature_auto_email"
      trigger_point = "(Commented for now) Background job to send GradReady feature related emails"
      category = "Student emails"
      recipient  = "All users after 7 days of enrolment"
    when "send_first_welcome_email"
      trigger_point = "On user signup"
      category = "Student emails"
      recipient  = "Student Enrolled"
    when "student_new_free_trail_enrolment"
      trigger_point = "On Enrolling for free trial if product version name does not include 'pre-employment' (Not in use)"
      category = "Enrolment"
      recipient  = "Student Enrolled"
    when "send_autoresponse"
      trigger_point = "Autoemail on tickets if enabled from admin to autoreply. For example holiday eamils "
      category = "Ticket"
      recipient  = "Student who raised ticket"
    end
    puts "---------------------> #{action} <------------------------"
    return trigger_point.downcase, category.downcase, recipient.downcase
  end

  # def self.get_category(email_type)
  #   email_type = email_type.gsub("Mailer", "")
  #   case email_type
  #   when "Announcement"
  #     result = "Announcement"
  #     trigger_name = "Announcement"
  #   when "BlogPost"
  #     result = "Blog Post"
  #     trigger_name = "New Blog Post"
  #   when "BookTutor"
  #     result = "Private Tutoring"
  #     trigger_name = "Private Tutoring Information"
  #   when "ContactForm"
  #     result = "Contact Form"
  #     trigger_name = "Inqury Contact Form"
  #   when "Courses"
  #     result = "Course Notification"
  #     trigger_name = "Course Notification"
  #   when "Enrolments"
  #     result = "Enrolment Process"
  #     trigger_name = "Course Purchased"
  #   when "EssayResponse"
  #     result = "Essay"
  #     trigger_name = "Essay Details"
  #   when "EssayTutor"
  #     result = "Essay"
  #     trigger_name = "Essay Details"
  #   when "JobApplication"
  #     result = "Job application"
  #     trigger_name = "Job application"
  #   when "ManualEmailAnnouncement"
  #     result = "Manual Email Announcement"
  #     trigger_name = "Manual Email Announcement"
  #   when "McqStem"
  #     result = "Essay"
  #     trigger_name = "Essay Details"
  #   when "MockExamEssay"
  #     result = "Essay"
  #     trigger_name = "Essay Details"
  #   when "Orders"
  #     result = "Payment Process"
  #     trigger_name = "Payment Confirmation"
  #   when "Rater"
  #     result = "Rating"
  #     trigger_name = "Rating"
  #   when "TextbookDelivery"
  #     result = "Payment Process"
  #     trigger_name = "Payment Confirmation"
  #   when "Ticket"
  #     result = "GC Support Tickets"
  #     trigger_name = "Support Ticket"
  #   when "User"
  #     result = "User"
  #     trigger_name = "Welcome Email"
  #   end
  # return result, trigger_name
  # end
end
